# version: '3.7'
# services:
#   mysql_db_container:
#     image: mysql:latest
#     command: --default-authentication-plugin=mysql_native_password
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword  # root账号密码
#     ports:
#       - 3306:3306
#     volumes:
#       - mysql_db_data_container:/var/lib/mysql
#   adminer_container:
#     image: adminer:latest
#     environment:
#       ADMINER_DEFAULT_SERVER: mysql_db_container
#     ports:
#       - 8080:8080

# volumes:
#   mysql_db_data_container:


version: '3.7'
services:
  mysql_db_container:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # root账号密码
      MYSQL_DATABASE: course  # 添加这行来自动创建数据库
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
  nuxt_app_container:
    container_name: nuxt_app
    restart: always
    #构建容器
    build:
      context: .
      # 自动输入Y防止造成编译卡死
      args:
        - "-y"
    ports:
      - "3004:3000"
    environment:
      DATABASE_URL: mysql://root:rootpassword@mysql_db_container:3306/course
      NUXT_BASE_URL: https://jsonplaceholder.typicode.com
      JSON_SECRET: aaabbbcccddd
    # command: >
    #   /bin/sh -c 'npm run migrate && npm run build && npm start'
    command: >
      /bin/sh -c '
        echo "Waiting for database..." &&
        sleep 10 &&
        npm run migrate &&
        echo "Migration completed" &&
        npm run seed &&
        echo "Seeding completed" &&
        npm run build &&
        echo "Build completed" &&
        npm start
      '
    depends_on:
      mysql_db_container:
        condition: service_healthy
  mongodb_container:
    image: mongo:5
    container_name: mongodb_service
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
volumes:
  mysql_db_data_container:
